#' Compute statistical correlation robustness test between samples
#'
#' @author Huiwen Zheng
#' @param group_list A list that contains multiple prop_distribution list generated by prop_distribution function, which at least contains bi_zero and prop_distribution.
#' @param ref An integer indicates the reference used in the comparison. Default set to 1, indicating the first proportion list is used as reference.
#' @param p.adj Significance level used in the asymptotic test.
#' @return A dataframe with gene pair names, type (either changed in sign or through statistical testing), absolute fold-change.
#' @export
#'
robustness2 <- function(group_list,ref=1,p.adj = 0.05){
  n_group <- length(group_list)
  # firstly find shared gene pairs
  gp_list <- list()
  for (n in 1:n_group){
    gp <- apply(group_list[[n]]$prop_distribution[,1:2],1,function(s)paste0(s[1],'_',s[2]))
    gp_list[[n]] <- gp
  }
  shared_corpair <- Reduce(intersect,gp_list)
  shared_pair <- cbind(sapply(shared_corpair,function(d)stringr::str_split(d,'_')[[1]][1]),sapply(shared_corpair,function(d)stringr::str_split(d,'_')[[1]][2]))
  # update each list with the shared gene pairs
  calc_RS <- function(x){
    u <- rowMeans(as.matrix(x$prop_distribution[,-1:-3]),na.rm = T)
    s <- matrixStats::rowSds(as.matrix(x$prop_distribution[,-1:-3]),na.rm = T)
    cv <- s/u
    x$prop_distribution[,3]/cv*x$bi_nonzero
  }
  for (n in 1:n_group){
    pp <- paste0(group_list[[n]]$prop_distribution$gene1,'_',group_list[[n]]$prop_distribution$gene2)
    share_index <- match(shared_corpair,pp )
    group_list[[n]]$prop_distribution <-  group_list[[n]]$prop_distribution[share_index,]
    group_list[[n]]$bi_nonzero <- group_list[[n]]$bi_nonzero[share_index]
  }
  RS_df <- matrix(ncol=n_group, nrow=length(shared_corpair))
  for (n in 1:n_group){
    group_list[[n]]$RS <-  calc_RS(group_list[[n]])
    RS_df[,n] <- calc_RS(group_list[[n]])
  }

  # identify DC genes
  # gene pair changed sign
  # grab all signs
  all_sign <- sapply(group_list,function(u)u$prop_distribution[,3])
  # at least one gene pair has changed sign
  sig_gp <- all_sign[apply(all_sign,1,function(s)abs(sum(s))<n_group),]
  index_sig_gp <- apply(all_sign,1,function(s)abs(sum(s))<n_group)
  cor_final1 <- cbind(group_list[[n]]$prop_distribution[index_sig_gp,1:2],rep('sign',sum(index_sig_gp)), abs(RS_df[index_sig_gp,-ref]/RS_df[index_sig_gp,ref]))
  colnames(cor_final1) <- c('gene1','gene2','type', paste0('diff',1:(n_group-1)))
  message(paste0('Identify ', nrow(cor_final1), ' gene pairs have correlation sign changed' ))

  prop_list_1 <- sapply(group_list,function(b)b$prop_distribution[!index_sig_gp,])
  RS_df1 <- RS_df[!index_sig_gp,]

  prop_names <-  prop_list_1[[1]][,1:2]
  prop_list_1 <- sapply(prop_list_1, function(g)g[,-1:-3])
  # force into a big matrix
  prop_test <- do.call(cbind.data.frame, prop_list_1)

  rownames(prop_test) <- NULL
  colnames(prop_test) <- NULL

  label <- rep(paste0("group",1:n_group),sapply(prop_list_1, ncol))
  # Performing asymptotic testing
  cv_p <- apply(prop_test,1,function(s){
    dat_cv <- data.frame(value=as.numeric(s), group = label)
    dat_cv <- na.omit(dat_cv)
    cvequality::asymptotic_test(x=dat_cv$value,y=dat_cv$group)$p_value
  })

  cv_p[is.na(cv_p)]=1 # remove NAs due to low SD
  cv_p_adj <- p.adjust(cv_p, method = 'BH')
  cor_final2 <- cbind(prop_names[cv_p_adj<p.adj,1:2],rep('DC',sum(cv_p_adj<p.adj)), abs(RS_df1[cv_p_adj<p.adj,-ref]/RS_df1[cv_p_adj<p.adj,ref]))
  message(paste0('Identify ', nrow(cor_final2), ' gene pairs differntially coexpressed' ))
colnames(cor_final2) <-  c('gene1','gene2','type', paste0('diff',1:(n_group-1)))

cor_final <- rbind(cor_final1,cor_final2)
rownames(cor_final) <- NULL
cor_final
}
