#' Compute statistical correlation robustness test between two samples
#'
#' @author Huiwen Zheng
#' @param prop_list1 A list generated by prop_distribution function, which at least contains bi_zero and prop_distribution.
#' #' @param prop_list2 A list generated by prop_distribution function, which at least contains bi_zero and prop_distribution.
#' @param p.adj Significance level used in the asymptotic test.
#' @return A dataframe with gene pair information, robustness score *(RS)*
#' @export
#'
robustness2 <- function(prop_list1,prop_list2, p.adj= 0.05){
bi_zero1 <- prop_list1[['bi_nonzero']]
local_cor1 <- prop_list1[['prop_distribution']]
test_mean1 <- rowMeans(as.matrix(local_cor1[,-1:-3]),na.rm = T)
test_sd1 <- matrixStats::rowSds(as.matrix(local_cor1[,-1:-3]),na.rm = T)
test_cv1 <- test_sd1/test_mean1
cor_summary1 <- cbind(local_cor1[,1:2],local_cor1[,3]/test_cv1*bi_zero1)

bi_zero2 <- prop_list2[['bi_nonzero']]
local_cor2 <- prop_list2[['prop_distribution']]
test_mean2 <- rowMeans(as.matrix(local_cor2[,-1:-3]),na.rm = T)
test_sd2 <- matrixStats::rowSds(as.matrix(local_cor2[,-1:-3]),na.rm = T)
test_cv2 <- test_sd2/test_mean2
cor_summary2 <- cbind(local_cor2[,1:2],local_cor2[,3]/test_cv2*bi_zero2)

# find shared gene pairs
shared_corpair <- intersect(apply(local_cor1[,1:2],1,function(s)paste0(s[1],'_',s[2])),apply(local_cor2[,1:2],1,function(s)paste0(s[1],'_',s[2])))
shared_pair <- cbind(sapply(shared_corpair,function(d)stringr::str_split(d,'_')[[1]][1]),sapply(shared_corpair,function(d)stringr::str_split(d,'_')[[1]][2]))
index <- c()
local_cor1_shared <- do.call('rbind',apply(shared_pair,1,function(z)local_cor1[local_cor1$gene1==z[1]&local_cor1$gene2==z[2],]))
local_cor2_shared <- do.call('rbind',apply(shared_pair,1,function(z)local_cor2[local_cor2$gene1==z[1]&local_cor2$gene2==z[2],]))
cor_summary1_shared <- do.call('rbind',apply(shared_pair,1,function(z)cor_summary1[cor_summary1$gene1==z[1]&cor_summary1$gene2==z[2],]))
cor_summary2_shared <- do.call('rbind',apply(shared_pair,1,function(z)cor_summary2[cor_summary2$gene1==z[1]&cor_summary2$gene2==z[2],]))


for (i in 1:nrow(local_cor1_shared)){
  if(local_cor1_shared[i,3]*local_cor2_shared[i,3]==-1){
    index = c(index,i)
  }
}

cor_summary1_shared <- cor_summary1_shared[-index,]
cor_summary2_shared <- cor_summary2_shared[-index,]
cor_final1 <- cbind(cor_summary1_shared[index,1:2],cor_summary1_shared[index,3]/cor_summary2_shared[index,3]*-1)
colnames(cor_final1) <- c('gene1','gene2','RS')

local_cor1 <- local_cor1_shared[-index,]
local_cor2 <- local_cor2_shared[-index,]

rownames(local_cor1) <- NULL
rownames(local_cor2) <- NULL

colnames(local_cor1) <- NULL
colnames(local_cor2) <- NULL
cv_p <- c()
for (j in 1:nrow(local_cor1)){
  a = as.numeric(local_cor1[j,-1:-3])
  a = a[!is.na(a)]
  b = as.numeric(local_cor2[j,-1:-3])
  b = b[!is.na(b)]

  dat_cv <- data.frame(value=c(a,b), group = rep(c("condition1",'condition2'),c(length(a),length(b))))
  cv_p <- c(cv_p,cvequality::asymptotic_test(x=dat_cv$value,y=dat_cv$group)$p_value)
}
cv_p_adj <- p.adjust(cv_p, method = 'BH')
cor_final2 <- cbind(cor_summary1_shared[cv_p_adj<p.adj,1:2],cor_summary1_shared[cv_p_adj<p.adj,3]/cor_summary2_shared[cv_p_adj<p.adj,3])
colnames(cor_final2) <- c('gene1','gene2','RS')

cor_final <- rbind(cor_final1,cor_final2)
rownames(cor_final) <- NULL
cor_final
}
