#' Compute statistical correlation robustness test
#' @author Huiwen Zheng
#' @param prop_list A list generated by prop_distribution function, which at least contains bi_zero and prop_distribution.
#' @param stats By default, performs asymptotic test for the equality of coefficients of variation to determine against null distribution.          If changes to FALSE, top *1%* most stably correlated gene pairs will be returned.
#' @param p.adj Significance level used in the asymptotic test.
#' @return A dataframe with gene pair information, robustness score *(RS)* and p.adj value.
#' @export

robustness <- function(prop_list,stats=T, p.adj= 0.1){
bi_zero <- prop_list[['bi_nonzero']]
local_cor <- prop_list[['prop_distribution']]
test_mean <- rowMeans(as.matrix(local_cor[,-1:-3]),na.rm = T)
test_sd <- matrixStats::rowSds(as.matrix(local_cor[,-1:-3]),na.rm = T)
test_cv <- test_sd/test_mean
cor_summary <- cbind(local_cor[,1:2],local_cor[,3]/test_cv*bi_zero)
if (stats==F){
  cor_summary <- cor_summary[abs(cor_summary[,3])>quantile(abs(cor_summary[,3]),0.01),]
  colnames(cor_summary) <- c('gene1','gene2','RS')
  cor_summary
}
else {
  null_dist <- unname(colMeans(as.matrix(local_cor[,-1:-3]),na.rm = T))
  cv_p = apply(local_cor[,-1:-3],1,function(a){
    dat_cv <- data.frame(value=c(as.numeric(na.omit(a)),null_dist), group = rep(c("gene",'reference'),c(length(na.omit(a)),length(null_dist))))
    cvequality::asymptotic_test(x=dat_cv$value,y=dat_cv$group)$p_value
  })
  cv_p_adj <- p.adjust(cv_p, method = 'BH')

  cor_summary <- cor_summary[(test_cv<(sd(null_dist)/mean(null_dist)))&cv_p_adj<p.adj,]

  cv_p_adj <- cv_p_adj[(test_cv<(sd(null_dist)/mean(null_dist)))&cv_p_adj<p.adj]
  cor_final <- cbind(cor_summary[,1:2],cor_summary[,3],cv_p_adj)

  colnames(cor_final) <- c('gene1','gene2','RS',"p.adj")
  cor_final
}

}
